# Generated by Django 2.1.15 on 2020-06-30 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='1', max_length=16)),
                ('f_owner', models.CharField(default='1', max_length=16)),
                ('f_size', models.BigIntegerField(default=0)),
                ('f_code', models.CharField(default='1234', max_length=4)),
                ('f_key', models.CharField(default=None, max_length=1024)),
                ('f_url', models.CharField(default='127.0.0.1:8000/static/file', max_length=256)),
                ('sort', models.CharField(default='others', max_length=256)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2020, 6, 30, 19, 19, 17, 191181))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('crypto_id', models.CharField(default='MD5', max_length=32)),
                ('key', models.CharField(max_length=1024)),
                ('file_url', models.CharField(default='127.0.0.1:8000/static/file', max_length=256)),
                ('has_confirmed', models.BooleanField(default=False)),
                ('max_space', models.BigIntegerField(default=2147483648)),
                ('remain_space', models.BigIntegerField(default=2147483648)),
            ],
            options={
                'verbose_name': 'people',
                'verbose_name_plural': 'people',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
