# Generated by Django 2.2 on 2020-09-04 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200630_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_owner', models.CharField(default='1', max_length=16)),
                ('g_size', models.BigIntegerField(default=0)),
                ('g_code', models.CharField(default='1234', max_length=4)),
                ('creat_time', models.DateTimeField(default=datetime.datetime(2020, 9, 4, 9, 48, 29, 571204))),
                ('g_file_url', models.CharField(default='127.0.0.1:8000/static/group', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='f_code',
        ),
        migrations.RemoveField(
            model_name='file',
            name='f_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='crypto_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 9, 48, 29, 571204)),
        ),
    ]
