# Generated by Django 2.2 on 2020-09-05 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200904_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='g_size',
            new_name='number',
        ),
        migrations.AddField(
            model_name='file',
            name='f_group',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='g_name',
            field=models.CharField(default=None, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 16, 39, 45, 597241)),
        ),
        migrations.AlterField(
            model_name='group',
            name='creat_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 16, 39, 45, 596663)),
        ),
    ]
