# Generated by Django 2.1.15 on 2020-09-07 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200906_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 17, 20, 43, 446312)),
        ),
        migrations.AlterField(
            model_name='group',
            name='creat_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 17, 20, 43, 446312)),
        ),
    ]
