# Generated by Django 2.1.15 on 2020-09-09 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200907_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='f_key',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='file',
            name='f_switch',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 19, 25, 786253)),
        ),
        migrations.AlterField(
            model_name='group',
            name='creat_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 17, 19, 25, 785166)),
        ),
    ]
