# Generated by Django 2.1.15 on 2020-09-09 20:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200909_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='f_url',
            field=models.CharField(default='D://upload', max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 20, 2, 13, 569009)),
        ),
        migrations.AlterField(
            model_name='group',
            name='creat_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 20, 2, 13, 569009)),
        ),
    ]
