# Generated by Django 2.1 on 2020-09-10 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200910_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 18, 37, 56, 452633)),
        ),
        migrations.AlterField(
            model_name='group',
            name='creat_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 18, 37, 56, 452633)),
        ),
    ]
